### ISSUE TITLE
[1.14.4]On dedicated server, equipping Rhodonite boots, armor, leggings, chestplate crashes player

### ISSUE THREAD

**Issue by abel1470** [vincentmet/Rhodonite#8]

**Comment by abel1470** [comment]
im new to all this bug reporting, I had the same error that happened in 1.15.2, when i equipped my rhodonite chestplate in my dedicated server it kicked me out, and when I tried to enter it again it said internal server error

**Comment by abel1470** [comment]
is this fine? ( don't know if it is my error log):
 at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:428) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerInventory.func_70440_f(I)Lnet/minecraft/item/ItemStack;
        at com.vincentmet.rhodonite.armor.RhodoniteHelmet.onArmorTick(RhodoniteHelmet.java:34) ~[?:1.14.4-1.1] {re:classloading}
        at net.minecraftforge.common.extensions.IForgeItemStack.onArmorTick(IForgeItemStack.java:289) ~[?:?] {re:classloading}
        at net.minecraft.entity.player.PlayerInventory.lambda$tick$0(PlayerInventory.java:269) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:269) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:492) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothpotiondmg,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?] {re:classloading,pl:accesstransformer:B}
        ... 8 more

**Comment by vincentmetevelis** [comment]
I probably need to bump the forge version for the mod

**Comment by abel1470** [comment]
Im using forge 28.1.96
